spring:
  profiles:
    active: dev

api:
  endpoint:
    base-url: /api/v1

security:
  oauth2:
    resourceserver:
      jwt:
        authorities-claim-name: authorities
        authority-prefix: ""

server:
  port: 80